# Generated by Django 5.2.8 on 2025-11-29 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('kinematics_profile', models.TextField(blank=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('ACTIVE', 'Active'), ('OFFLINE', 'Offline'), ('ERROR', 'Error'), ('MAINTENANCE', 'Under maintenance')], default='IDLE', max_length=20)),
                ('safety_envelope', models.JSONField(blank=True, null=True)),
                ('calibration_notes', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robots',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('INSPECTION', 'Inspection'), ('CALIBRATION', 'Calibration')], default='INSPECTION', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='robot.robot')),
            ],
            options={
                'verbose_name': 'Maintenance event',
                'verbose_name_plural': 'Maintenance events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_capabilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='robot.robot')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'deadline', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUCTION_MANAGER', 'Production manager'), ('OPERATOR', 'Operator'), ('MAINTENANCE_ENGINEER', 'Maintenance engineer'), ('AUDITOR', 'Auditor / Analytics'), ('ADMIN', 'Administrator')], default='OPERATOR', max_length=40)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='robot_audit_target__c73fab_idx'), models.Index(fields=['timestamp'], name='robot_audit_timesta_17c426_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction_type', models.CharField(choices=[('ANOMALY_SCORE', 'Anomaly score'), ('RUL', 'Remaining useful life')], default='ANOMALY_SCORE', max_length=30)),
                ('value', models.FloatField()),
                ('model_version', models.CharField(max_length=100)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='robot.robot')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['robot', 'prediction_type', 'timestamp'], name='robot_predi_robot_i_b285b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_value', models.FloatField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='robot.robot')),
            ],
            options={
                'verbose_name': 'Telemetry point',
                'verbose_name_plural': 'Telemetry points',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['robot', 'timestamp'], name='robot_telem_robot_i_5fc2b4_idx'), models.Index(fields=['metric_name', 'timestamp'], name='robot_telem_metric__47e98c_idx')],
            },
        ),
    ]
